# Generated by Django 3.2.8 on 2021-10-23 11:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('max_adult', models.IntegerField()),
                ('max_child', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('status', models.CharField(default='available', max_length=128)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='media/room_image/', verbose_name='Image')),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'dashboard_room',
            },
        ),
        migrations.CreateModel(
            name='Room_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10, unique=True)),
                ('reserved', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room')),
            ],
            options={
                'verbose_name': 'RoomsNo',
                'verbose_name_plural': 'RoomsNos',
                'db_table': 'dashboard_room_num',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'dashboard_offer_room',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, default=datetime.datetime(2021, 10, 23, 11, 21, 17, 717706), null=True)),
                ('payment_status', models.CharField(max_length=128)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('extra_bed', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_type', models.CharField(max_length=128)),
                ('reserved_rooms', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room')),
                ('room_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room_num')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'db_table': 'dashboard_booking',
            },
        ),
    ]
