# Generated by Django 3.2.8 on 2021-10-25 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_booking_booking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('extra_bed', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'booked room',
                'verbose_name_plural': 'booked rooms',
                'db_table': 'dashboard_booked_room',
            },
        ),
        migrations.CreateModel(
            name='BookedRoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_rooms', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'booked room type',
                'verbose_name_plural': 'booked room types',
                'db_table': 'dashboard_booked_room_type',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='child',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='extra_bed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reserved_rooms',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_num',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 25, 10, 30, 4, 598281), null=True),
        ),
        migrations.DeleteModel(
            name='Room_num',
        ),
        migrations.AddField(
            model_name='bookedroomtype',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking'),
        ),
        migrations.AddField(
            model_name='bookedroomtype',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
        ),
        migrations.AddField(
            model_name='bookedroom',
            name='booked_room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bookedroomtype'),
        ),
    ]
