# Generated by Django 3.2.8 on 2021-10-25 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211025_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 25, 14, 4, 24, 469287), null=True),
        ),
    ]
