# Generated by Django 3.2.8 on 2021-10-26 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211025_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='extra_bed_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 6, 47, 26, 199891), null=True),
        ),
    ]
