# Generated by Django 3.2.8 on 2021-10-26 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211026_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedroom',
            name='extra_bed_price',
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 7, 4, 12, 456190), null=True),
        ),
    ]
