# Generated by Django 3.2.8 on 2021-10-26 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211026_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroomtype',
            name='extra_bed_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookedroomtype',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookedroomtype',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 10, 32, 30, 820284), null=True),
        ),
    ]
