# Generated by Django 3.2.8 on 2021-10-26 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211026_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 10, 33, 2, 195668), null=True),
        ),
    ]
