# Generated by Django 3.2.8 on 2021-10-26 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20211026_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 10, 34, 20, 558516), null=True),
        ),
    ]
