# Generated by Django 3.2.8 on 2021-10-29 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211026_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_extra_bed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 7, 11, 44, 54924), null=True),
        ),
    ]
