# Generated by Django 3.2.8 on 2021-10-29 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20211029_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 8, 40, 51, 694895), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_extra_bed',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
