# Generated by Django 3.2.8 on 2021-10-29 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20211029_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 10, 45, 22, 614265), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_extra_bed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
