# Generated by Django 3.2.8 on 2021-10-29 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20211029_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='isBooking_confirmed',
            new_name='is_Booking_confirmed',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 29, 13, 17, 21, 514107), null=True),
        ),
    ]
