# Generated by Django 3.2.8 on 2021-10-30 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20211029_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_extra_bed',
            new_name='total_extra_bed_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 30, 9, 8, 40, 701784), null=True),
        ),
    ]
