# Generated by Django 3.2.8 on 2021-11-02 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20211102_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='offer_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 2, 7, 50, 39, 755565), null=True),
        ),
    ]
