# Generated by Django 3.2.8 on 2021-11-09 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20211102_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 9, 9, 15, 1, 180116), null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(default="2021-11-04"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(default="2021-11-04"),
            preserve_default=False,
        ),
    ]
