# Generated by Django 3.2.8 on 2021-11-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_booking_booking_date'),
    ]

    operations = [
    ]
