# Generated by Django 3.2.8 on 2021-11-09 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_merge_20211109_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 9, 11, 41, 31, 293699), null=True),
        ),
    ]
