# Generated by Django 3.2.8 on 2021-11-10 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20211110_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 10, 8, 22, 41, 920518), null=True),
        ),
    ]
