# Generated by Django 3.2.8 on 2021-11-10 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20211110_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 10, 9, 40, 49, 598356), null=True),
        ),
    ]
