# Generated by Django 3.2.8 on 2021-11-10 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20211110_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 10, 10, 46, 52, 711738), null=True),
        ),
    ]
