# Generated by Django 3.2.8 on 2021-11-16 06:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20211110_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout_date_display',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 16, 12, 19, 5, 645575), null=True),
        ),
    ]
