# Generated by Django 3.2.8 on 2021-11-18 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20211118_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 18, 15, 17, 38, 783172), null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking'),
        ),
    ]
