# Generated by Django 3.2.8 on 2021-11-23 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20211123_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroomtype',
            name='total_offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 23, 11, 29, 11, 949819), null=True),
        ),
    ]
