# Generated by Django 3.2.8 on 2021-11-23 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20211123_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroomtype',
            name='offer_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 23, 11, 32, 10, 254504), null=True),
        ),
    ]
